// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLjWQldK8r4NFQhi0fJaFwQGth66dHpA',
    appId: '1:362639636055:web:25246dffadd54a38085512',
    messagingSenderId: '362639636055',
    projectId: 'aththatu001',
    authDomain: 'aththatu001.firebaseapp.com',
    storageBucket: 'aththatu001.firebasestorage.app',
    measurementId: 'G-C59EP4CYLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXaFOkXUNxkMYPDAbIrGsmIiluv0U9hHk',
    appId: '1:362639636055:android:2178a8bbfe72cc87085512',
    messagingSenderId: '362639636055',
    projectId: 'aththatu001',
    storageBucket: 'aththatu001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEuSze5E3yk4YCzD4P3rLxVS1UBBrHUJU',
    appId: '1:362639636055:ios:256cea31554cea3b085512',
    messagingSenderId: '362639636055',
    projectId: 'aththatu001',
    storageBucket: 'aththatu001.firebasestorage.app',
    iosClientId: '362639636055-shgl9qo6a0rf7aupkb8l4pj07ag29o1m.apps.googleusercontent.com',
    iosBundleId: 'com.devalliance.aththatu',
  );
}
